### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by chroventer** [dirigeants/klasa#1061] opened 2020-06-23 06:35 UTC
![image](https://user-images.githubusercontent.com/34645569/85368895-eff97b00-b4e0-11ea-84fb-1d70bf97950f.png)

Error:

```
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data
```

**Comment by Relms12345** [comment] 2020-06-23 06:37
Duplicate of #1039

**Closed** 2020-06-23 06:39 UTC
