### ISSUE TITLE
Suggestion: RegExp prefix's

### ISSUE THREAD

**Issue by MrJacz** [dirigeants/klasa#94] opened 2017-11-25 16:25 UTC
A way to be able to have custom Prefix with regex's aka `this.client.config.prefix` could be `new RegExp(/!/g)` for example

**Comment by bdistin** [comment] 2017-11-25 16:41
Uh, this was a thing... If it's broken, that's a bug.

**Comment by MrJacz** [comment] 2017-11-25 18:56
Confirmed bug

**Comment by kyranet** [comment] 2017-11-25 18:58
`this.client.config.prefix` has never been RegExp but `string`/`string[]`. This suggestion breaks several pieces including SettingGateway. Althought SGv2 will just throw a [TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError).

**Comment by MrJacz** [comment] 2017-11-25 19:01
I'm sure it was a thing in August I remember using it but I could be tripping this might break SGv2 but maybe there could be a RegexPrefix option in KlasaClientConfig so that RegexPrefix is the main prefix that couldn't be overridden aka `Hey Skyra, ping` would work always even if you used conf to change the prefix so it is not overridable.

**Comment by kyranet** [comment] 2017-11-25 19:13
Just like Komada 0.19.7's usage were so bugged the repeator tag was useless and it was capturing from the argument's position to the end (infinite catching), it got fixed in 0.20.0 with Ao's rewrite and that behaviour dissapeared. There has not been an infinite catching feature in Komada, nor in Klasa, although a bug allowed it to exist.

Same happens here with the prefixes, `this.client.config.prefix` being a RegExp (but guild prefixes defaulted to `string`|`string[]`). That was an unintended behaviour that worked due to a bug, but since the bug is now fixed, that does not longer work.

**Comment by MrJacz** [comment] 2017-11-25 19:19
I see

**Comment by MrJacz** [comment] 2017-11-25 19:27
@kyranet What is your opinion on the `regexPrefix` option in KlasaClientConfig? I think it would become handy

**Comment by MrJacz** [comment] 2017-11-25 19:32
as PrefixMention shouldn't be overidden and is only meant for mentioni prefix for the bot...

**Comment by kyranet** [comment] 2017-11-25 19:43
My opinion is that `regexPrefix` is a nice-to-have feature, but most developers will not find it handy. (Keep in mind that [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) is a feature that many newbie developers find hard to use.

**Comment by MrJacz** [comment] 2017-11-25 19:51
I can agree with it being a nice feature to have and very true that noobie developers dont know the power of Regular expresions

**Closed** 2017-11-30 22:38 UTC
Labels: Meta: Proposal
